app = "bantuin"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"

[processes]
  app = "bin/rails server"
  worker = "bundle exec sidekiq"

[env]
  TZ = "Asia/Jakarta"

[[services]]
  processes = ["worker"]
  count = 1

[http_service]
  processes = ["app"]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0


[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
