development:
  cloud_name: "dis2k0keq"
  api_key: "578344134129924"
  api_secret: ENV['CLOUDINARY_SECRET']
  secure: true
  
production:
  cloud_name: "dis2k0keq"
  api_key: "578344134129924"
  api_secret: ENV['CLOUDINARY_SECRET']
  secure: true