development:
  cloud_name: "dis2k0keq"
  api_key: "578344134129924"
  api_secret: "8kEXc4Uf4l38s3kM51xIbOmH708"
  secure: true
  
production:
  cloud_name: "dis2k0keq"
  api_key: "578344134129924"
  api_secret: "8kEXc4Uf4l38s3kM51xIbOmH708"
  secure: true