:scheduler:
  :listened_queues:
    - default
  :schedule:
    reminder_worker:
      cron: '* * * * * Asia/Jakarta'
      class: ReminderWorker
    
    repeater_worker:
      cron: '* * * * * Asia/Jakarta'
      class: RepeaterWorker

    status_worker:
      cron: '* * * * * Asia/Jakarta'
      class: StatusWorker